site_name: Design Patterns
repo_url: https://github.com/programgames/DesignPattern
repo_name: Github
site_description: Présentation des design patterns
site_author: Julien Marcon
remote_branch: gh-pages
dev_addr: 'localhost:8010'
theme: readthedocs
nav:
    - Home: index.md
    - About: about.md
    - Création :
          - Abstract Factory: abstract-factory.md
          - Factory : factory.md
          - Builder: builder.md
          - Prototype: prototype.md
          - Singleton: singleton.md
    - Structurel:
          - Adapter: adapter.md
plugins:
    - macros